### ISSUE TITLE
Cannot resolve module - deferred.ts

### ISSUE THREAD

**Issue by kishorevaishnav** [syumai/dinatra#24] opened 2019-02-20 08:07 UTC
I might be reporting this too early, but I am getting some error.

```
↳ deno --version
deno: 0.3.0
v8: 7.4.158
typescript: 3.2.1
```

```
↳ deno index.ts
Compiling file:///Users/kishore/proj/github.com/kishorevaishnav/deno-weight-tracker/index.ts
Downloading https://denopkg.com/syumai/dinatra/mod.ts...
Downloading https://deno.land/x/std/http/server.ts...
Downloading https://deno.land/x/std/util/deferred.ts... NOT FOUND
Uncaught NotFound: Cannot resolve module "https://deno.land/x/std/util/deferred.ts" from "/Users/kishore/Library/Caches/deno/deps/https/denopkg.com/syumai/dinatra/mod.ts"
    at DenoError (deno/js/errors.ts:22:5)
    at maybeError (deno/js/errors.ts:41:12)
    at maybeThrowError (deno/js/errors.ts:29:15)
    at sendSync (deno/js/dispatch.ts:67:5)
    at fetchModuleMetaData (deno/js/os.ts:80:19)
    at _resolveModule (deno/js/compiler.ts:253:38)
    at resolveModuleNames (deno/js/compiler.ts:490:31)
    at compilerHost.resolveModuleNames (deno/third_party/node_modules/typescript/lib/typescript.js:32750:71)
    at resolveModuleNamesWorker (deno/third_party/node_modules/typescript/lib/typescript.js:20688:69)
    at resolveModuleNamesReusingOldState (deno/third_party/node_modules/typescript/lib/typescript.js:20909:20)
```

the `index.ts` is same as the example in your readme.

**Comment by kishorevaishnav** [comment] 2019-02-20 08:10
I think I found the problem. I guess its the problem with the std_util not added to the deno std registry. https://github.com/denoland/registry/pull/54

**Comment by syumai** [comment] 2019-02-20 08:12
HI, thanks! I think the problem is this: https://github.com/denoland/deno_std/pull/206 a PR merged at 14h ago.
I'll fix the version of deno_std to solve this problem.

**Comment by syumai** [comment] 2019-02-20 08:18
I'm trying to fix this in https://github.com/syumai/dinatra/pull/25 .

**Comment by syumai** [comment] 2019-02-20 08:19
@kishorevaishnav The problem has been solved. Thanks!

**Closed** 2019-02-20 08:19 UTC

**Comment by kishorevaishnav** [comment] 2019-02-20 08:22
Cool. Thanks. It worked like charm!!!
